name: sp500-feature-pipelines

on:
  workflow_dispatch:
  schedule:
    - cron: '11 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
          platform: 'linux-20.04'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: set modal token
        run: |
          modal token set --token-id ak-j3SJDzdOMf5R4gSPk5ENG6 --token-secret as-stKZ2VIgXZw3bqoe1TRvCN 
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python ./feature_pipeline_daily.py
